name: build-pipeline

on:
  push:
    tags:
      - 'v[1-9]+.[0-9]+.[0-9]+'

env:
  PYTHON_IMAGE: 3.9

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_IMAGE }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements_dev.txt
          pip list

      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ env.PYTHON_IMAGE }}-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}

  tox_tests:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openweathermap/deker/deker-embedded/tox:latest
      env:
        PACKAGE_VERSION: ${{ github.REF_NAME }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set python versions
        run:  pyenv global 3.9 3.10 3.11

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install tox
        run: |
          env
          pip install tox
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
      - name: Run tox tests
        run: |
          env
          tox
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
          PACKAGE_VERSION: ${{ github.REF_NAME }}

  build_docs:
    needs: tox_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load virtual environment
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ env.PYTHON_IMAGE }}-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
      - name: Make Sphinx docs
        run: |
          source venv/bin/activate
          doc8 --config pyproject.toml docs/deker
          cd ./docs
          make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  publish_docs:
    needs: build_docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: docs/_build/html

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: tox_tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        run: |
          pip wheel -w ./wheelhouse .

  build_sdist:
    needs: tox_tests
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: |
          pipx install poetry
          poetry build -f sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/deker

    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
